---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespaces.yaml
  # Flux-Kustomizations
  - ./metallb/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./wireguard/ks.yaml
  # Temporarily disabled until we have a working k8s-gateway
  # - ./k8s-gateway/ks.yaml
