apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: gregoryszkudlarek@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-staging-key
    # Add a single challenge solver, HTTP01 using nginx
    preferredChain: "ISRG Root X1"
    solvers:
    - dns01:
        cloudflare:
          email: gregoryszkudlarek@gmail.com
          apiTokenSecretRef:
            key: api-token
            name: cloudflare-api-token
