apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: media
spec:
  storageClassName: nfs-00
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100000Gi
