apiVersion: v1
kind: PersistentVolume
metadata:
  name: scratch-pv
spec:
  capacity:
    storage: 115Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  claimRef:
    name: scratch-pvc
    namespace: media
  storageClassName: local-path
  local:
    path: /scratch
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - control-00
