apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:9r0GsP4aErtqRflOXQb1R9rrowNPA8DzzP6fx+X13wpg9GaIh9BK2mvfU4buaek3Ahlb/2NTDS5TwuuybQq3hOrk/y2JholLinSh5N7wXVK1HZGIpGsShaFzDJkfKoYqNUfjVfaPnrdhxQGaBe3LVzvpbelFaW9xZPCKvoQOFzqT8EynQ77/0goqevU5SRkucxLv9jPtG5lMwBnlgwN5Z0ItXD0KdLhbBe3Xbiy4Mh8fuvnkjTdzX2Xkui57XigHKJkzWO6YUwLuIn3irlqMCK12BvccwWh7FJ8w7lzd01d98SlCHHzcrwLYOBQ7qF9OkQhaJWduArlsXlbor11Gjp0f1b3jA60w+bIx8OvNu88obK+6+EFHcRmsrFoLls/w82iWwCh0eXeBmNI4tOxT/feswXB0qgX+f4GEa304Qa3abcuXF+IxhZCPKxD5Xh9fAb5FGPRczYsGaHQziTzllM+Y5ZDcVh19BVdYGscOTD9J+sWddgdjMUx4os8WgBYWCiAluFUP5dkgHWQfT5ke2Nq8jiXfM4dsrnh0ok6VI6dc1R46qU3tdk+aqIKNXGca26mBI6X1Pqa09ztRypqoTtYGPScjrbMHZnMQpJBXOpmV3dDOZVrbiARZBAX1Sq3ki77cunUHaOnlS9sqNOZc/Ey0bRhiwlTwiNJgsnc95Z6zIVjbhIrlndsEOKRRf9GyAnmvCHBJZVmx+5l+Pnen74pvti41MJcOySs/wRruGV0RNYw6usXtuGFRsB0jZScON8ZRac4eEMJ4m7ttPvTr0N9vvtI3R1/JI4rAuaDlDNZFNQlklIfy3Gp//F32jQVZRkukbYC9gyVP4APqm5PH7g+p9jjjKtqV7bz65ZO8bCtSM/1td+vjp1PJTsuxfILwTSxOEeM6zUP5DMD5IfE11o3S1fZGiDLSSk+lfhHDgBvwjbPLviqU2sVreGSB/a0jK9axjTTOmsDMLJ8M3wWZsgsTgjW5QdlaCqGO/3p9yF6rSITuipgNcI9qUneE6H3zsmC1giYeyT4F5XcpwYNbBfiZxqEb0WoBLoXQcZJLlxZ8+oefYMI70yY93nR/5HUssS1vm4s+jy/3Ed7YRwT1D3RNTFDtPAOyyEiPyb/AedXv8OvHz+E57+rzTrWZk3GyZbdBxVMjZ8drdysm4TJ8Ee5Aca7jdDw8n/Xo3tWJvbT649K/dntOb7WiWSk0iHVD4fF66NPzoz4c/aSgq6P4N7Akkb++CUygRj44czCoH9rLjAi5K8S6dCI4onLHR3KcIEueO5jF8aouQP/FZ0E1Q/qU5hD/dk5/lqAttHA9GErZ7dtWUUzHbQ3vBxCO1s5Klv045y4iu5Kfy6zQPPupIOF5Bwefeaj210Qw9MYg57om7z8CrMRMZf9ed71N6DnXza8fYRgDQppbTvmMWDefSgbqNpwBIonWDLclkRwmF9I167jeelVgPLe0yZXSXj3zB64NoSvnQK7ZCA4NEo76YoyssKHyW8VE3nj5L0Bca0RI9x5MUQ+/hgIwGbodrS+mDZWUpN+YG8HDyJRJWFbXfku7iPOjfozI6L21cV8gxDHwoEi1gMpDfB7cypJ1VY7BhF7jIQIKgJmEQwvFt8/RdEut1ul9nAsB56NWkNBbiWzv1I3gQ8dvPibMARRygOvosPJPQGZ0RHpOoAOh8W50AqjF5OHuJvjJuy1Xk9ytgwSjyuNViSNYjbv0G6XZU/cmUOAdScMzy0y5dMtn46/7MJPNU7TkEI6hf4c8J5bAOKcWbv2kpNaqgypYinQJyV8YT8T8/Dow35bI8KDuoYRIne0qjMLk7i+vKUZ1y/q2wNxlVEjWbcEGhg0Nt2TBMGrCLo/c02rMQ5QszB1d5Mx/Phn8P6n5g8g1wO5ZVR9KE/y69xOhyckFABiqI/prDav9F7/l8qxm1ras/CohcCvtRxo3fNXz7Bd6gABVqKfbnP/+M+pQMHLpBJVmTTabpWtWcwKWo2s6MXbE0fc3ScusYnm1OP/Q/ShE3Ob3cc2jkpzkvtd8,iv:LpDkG11NdKCsLiVX8lRI7HsF57FfGZZx6Qea4u+yK1A=,tag:UFO4e91Zy5ShstJDRzItlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10tvu775rkn2seez6kkvkdgd7almegdkx5ajqaln5cym80pzspd9sfp3sap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUVkzRGhUeGFwdjZQMDU3
            OHdzdE9YMlBrbUpkU0gvZ0RqWTNnS0F6cUg0CldFVENMV0Fiek9JMHVhSE1oa05T
            Mm9HYmlyeWZlM2tNRGU0OEhaZFdDeXcKLS0tIFN6NTV2c3FDaXlidExrQUYrdmE5
            RUgva1RTVnNVVXJNQTc3N0h6L2lPV0EKzu3Rb3EFZnukP9Ebj9rmRM0aXwo672MG
            eCxMRYSI3l8xtlZgMmi30WwTrZ9MvgHRkTY3Ww2rxqvdRXQdZol+Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T16:17:23Z"
    mac: ENC[AES256_GCM,data:Grrhqa61z+8W/hxbG2BRdVqg9oScVrJ5NXSmsvEOSB7QyFyNLRw55uohRdUA0GtSOBP57WznSDLAcCe+BBZ4R7z1uRGoOn2tJ76+fc65QVg7plbzS1w5gtQLPAvUeTrepaOHNYf4mIxN4Cb0k4kZ5yjNfQyJ+iwEUILOk65Be+o=,iv:6sdebkrjZo0l2629/1ad1PcExFxKnrtr7V3eqnL17rI=,tag:ULR2nLAujCcF6pj/QEeW8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
