apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
data:
    token: ENC[AES256_GCM,data:7UufxmsGcodYTX1c1GDkuzssZPx2n3+3DBZN2AnTKcMUpsgv0WgaVwcNO8jnI7Bufn+burUeekcYykboXG3y1k340IQ0ubQGoq0lTXjDosDS54D2sOuNakwtjobro6hJq28GkheOmEws8kqsvQRVnUDw4/FVlALRMZI6LwI++XWvTZ9JpgQPG665JtD0n2aVn8lfAroIwZdCU3vMi+GAn9vWzZUfQMdtHypQZoSqLYm8w4oDjhg6Wax2IxQ+pCLyAKCg9ftA61zjUOfCuKv2gdgE0kYrTQSEcTSmj84+hJrfRAIDMTfuzfsvbookEQpvNM5SrfkV/QwsQORW2OYGDqL9dJWE1qMKHbFx8mCkWJqugvR5MxcTaRrsMWQGaGgBUASN4JGIR204o+YYjhRHXVZOnqgnCWfCCmP6JRSMIisWXBCi2PUn4jY6bvsrPsW8zUc6GL6FEBICGR4Fh5yK/4lDamfKZMS/PvfDxAoU6nOpRhWLZxTwExcZ267mbh11cEeQb0RTNFDMoAubjRqZvTGJ5HwEgyGZYWM7gBTePvbQVwnDMijWcYEkisnysaixogwaBYQwXw8eNHxbddyT6eU/jIjEfh4hacn0bFe7v9DtT4Vi9gHvr7RDchwtsAHVb7OUqLu3/tsqBif2g1lSNPvh9cltltxhdBNNgn4h4PDXRUGcirrPpn4H2e2Ru3lyEthIh/9tzbSJGxw1iMAxYtpPeAVYEdYgt+cPOPUya65mbbQeJ7vf/keFaB7AX/ukhki0aEsMCOVoH7QXxQL3lNUHB2XELOkoOlVS5cwaG5ZblgqZWr01LUGrDZkI+TE6p2FTVnVsvD+T2C1K0q/WruGluObWMiqXqUCEQ/VTXLepjhBzguLfDBAr0vRcKIS6nwpCV+vkvFlRF1aR4/YyyzBwt1TJvJp8HmTom0nezlR4KJSseaFCbm//ekjwOfotZYkLBPLog6lTdb0NH636wOI8nrfw5Oy9NTbNPGXOV0d/YOnn9J1Mvrdl8AW7Ib5Fkv1lVtvajmo/EsVKUVgWbpPxbMjXPw7gZW0duKuIGq3JlrS/CfxYdYZPdsyTtc2tmGA8gVmGaqQIuFp0wrqdrk/dsfz05n/wirJY/NaGrC+6syOUbnwNMPdaILQ=,iv:oBQ1B8fdp6krNpLSJQZWSnLYM7/ZaIqKMDwyOixmXQo=,tag:ar/X3tnihhVZ9yFQA7na/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10tvu775rkn2seez6kkvkdgd7almegdkx5ajqaln5cym80pzspd9sfp3sap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNTl5QjNOTkcxNk9qblh5
            blpNQk42K2E1eTQ0blJnQnNjbnJGVWloc1E0ClFaUWRPa1JQY2U0cHhNUzhobXFt
            RFBlYmRKK2p0c2JwU0tJRzhMck91dEEKLS0tIGdoR0JwNk1hN3REZitiYnFyalFH
            VFgrUFFNa09uMTVDVVIzYVBOUFZoWFEKJCQl3S1vRRHD3IYz0htkH2vPdUPc1BUq
            4tXOaVHRJ6OrAKLoaaQS3tFdIXYeUSqlSur/+jje25mZLvxUJ9cgEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T13:55:27Z"
    mac: ENC[AES256_GCM,data:5omxao8EzjAHQVLrjlQndIBdNAjNRfgqqPABVE3u+PX35xcfuVzSUq1r1yq8wH80EXmHexo4UVFDAxyGioAlmNBjCzESZPFCjmG2HOm/Fy/pXlrVfeOmEuBBWsQ/ImxXDaG6wrePQ3VxCNt3/e8FKR/aiNt1TIWi2h9/X28bv48=,iv:c1o9cZjKXTzDzYiTUnQxar/I8o4HffmcdBLQTUmXs1Y=,tag:89TcgFLJJ3Zu3v0lbN2X3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
