apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
data:
    1password-credentials.json: ENC[AES256_GCM,data:xc4XhlY9fg+BTXdetsNJgrVzTCw+WM6GBJZb5eQY33xvt2STY5yvNC1zGoki8k1pSUAaIvHpe65NJSFphvv1VPx2p2g7uhzDc9tGbVzpKdMV6gR8Ve+BYPVlpjZX7NXfDTSEku4zCLsETakFLm4GpBc2YsIB3PfTSPg+Ju3tBSJjarYqgEaZVw1/SgOJ93hhx2ww50rGMaYl2QoC6JWFilZu8Od0LGXM83D9DuGO4RI5LSZVV0FlfNTLm7FEMoXNC+jJriIbgpLPVzz39u/rQHKQ/EVc0oiY2Cw2JReOPs47YNrkQ0oc4uLEH4OmW9/LQwazdXPTkvJH88EmZ1CPVbLx/xMIE1TfguJCjYKSpvB3q6FdvmDpdxYW9vZV9OpNz5XXMr2V3jj4+3nh5gfEPKCvVVidgmajV6s2XkYYgIbIB3RVoBOBeZHVdr35wPZTAFT5UEqIYLLmuiSgGuNCJIShTJhvmv3nDWSG9V+/Y/Xdp5o7nKvslCgcVdtFGOFNx8SdhtsLl8F/QUoZUXM4fK0UXQG1Byspk2TjKhA8q8JZNZCf+WWxW9FkBTgoUK2b1npH/O75kvCky6fJj40s9P9KA/3eucFpQUfWoVl+TdhcgaEVWbQK2CHWDA7GGJcAyMnzg3n+2WMNqaScjpKEwDbSGX8cVSkaBdTdzYCy39C+AxpRQUaVZ8OiK28k/pEotTb/ytiro1eTWo3IHUFVW7EFrRp1tRXljmQYLPHqJ06WDIZ676eoCRamud/z7uwT0ZdD0MBExKbwUC6JPfDp7BrNmYCUyHTKXvCzmHauFIJc2yepJL4iw64ssb6mJDctR9XQH1ADYI1bXOKzamUDb7xC+O8XRB9OjzrZ5TIXdgI0laDbpikBFIM1jqQyAOwNIvTv8jj0n1OXxybkKxQTQQ3hFlPRCfeOvnqlRDDBDOq6Dd2Dd3SBVHrubvGTOEtSHDoLgQ6cVjozecgPV2XwT7CCqCZq21SIiNWNEhU87m1arQaUZwPo1iTrQG2sS/MgFz4tdnkYaa1zXgBcmuhxJDPhjDfNPpsEeJa+1L/GORjb64+G2pM4t634/ketxoBDYJksNbHmfmivWf/JHtg8iieoyg26FDuBKhJjocfqgrzf58u2ysO9PSPZD1ELJI3Vwqv8eSvgEBpNk4/cT9xsY7nRn1fz6e7a/EmzGlExgnR89iAEWLGX3Lz451q0VPxRfhNEgH+GfzqCaZuu0IW4VBRC1sz4XDixJ/+QF8iyAVXShK3hjgjvv3O11lwLv3Vkk1EwvOnwewhu9AAMcr9zR1vC0ivfulvFS9GTGdFhMiw/sgnL0kK0tRvNnzbYpY81oP0rKVYV58r/qsE2KiZkzv2Q2zYhFACwM9lCrf4ZlgUBNMKzOsXkbvO22ir36gSQdS8CPTrIA8ORCvGs/0tPmuMydmcbLhJbgrHZfo4/SRI9pIHHjkfhGfR3OvtVwPZFUaodZTcZ1Xqd+kD4Vt86lMpu8svP2EeY7QOI4O/t9+h9Zrn7GAVLH7kgYCzwMgh4NGPUlxpN6RDaX5Hfr1JwRpDUPdPHsXt6KBv1vgjnUh5rm30BFXx3FoLZh4AyydVM5Y23+S0yoMcGXqMLHflqf4aBzA3hB6AwVkc8KWtNnOjnj8A6l/0fufClr1i9Sl1PjG8FEfUmHpWsGWbRt+Qda3FZ6YXNmwHzEqFpKhBUhP8C7vtzPFZchhrgHXn8Jd5QSbMg0GG2QXTls6U85yJ/Sn80+zxT5ORJhuFmdJdkMtIhATbRTiUg6itAFD68usme7+upgnhQewS/GA4Ye9eLD429huRVmXVDLDflOif8kCiigFQ/ieZe4rUtZle+v0SOdjcPXt/72a8eBCMvE+/DXqXO7YhJ+EC6uGAxXbrJKLrk2sGDkLQwkxfPNvyvf6dgQdWxLeS8Vi/3FgDz6wuFAVjKRsm2ZLhrrW5joLIk2Ni+VNzlNFnkDzWdrpJplElycK/Fg1nmsLz/h4zcqzcgPA==,iv:L9+abvyGg8b2sBR4qt+84qE2rlBkpyO1b3AGCbu5vQs=,tag:LgMS1kHuVHLIzCaOtunK2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10tvu775rkn2seez6kkvkdgd7almegdkx5ajqaln5cym80pzspd9sfp3sap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwN1RjVTQ4cS8yZDBmWHd4
            bXRLRW9yd2dFRjFBRkxtUGo5dmVZWlM3TmtZCnpFdk9rVTdLUUV6WVY2L1k3VXdx
            cFhFL3Nudk9XUzJVbmpnN1AxRHhqc3MKLS0tIGNaYjNYM1FpZ1hXNUR4TFdjeFc2
            VFJHcmdjNmZaekEzRm8vQkJTeDhtVzAKeYqCt10XB5tDNqErZK6btmPiMJBu9T0k
            oQK0YQQKB/K1WzlFSo/I6uzqsICA9l2OxYowAwFy+sHC4aoUQQuqOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T14:35:49Z"
    mac: ENC[AES256_GCM,data:K+NZuQ75GReDrXBSIGiFJxYKZYT0f7d6Lo/7qwkD5D8Na1xdVkYFeAJtGTVFR54mlNSDr3kqgeFbjNTvnmtTLW1d7eczGBoHe6fheE0RUYo5b2m2yocJ2Zer2BQfkQYgz3X4rY0HEPWPwrjVuja4wfCzriCVA4Fef626SNnzKC0=,iv:YV+MPVUHbsLHhuB/IyhRoxdiha80UXQCbQDQYXxZ4iw=,tag:Z+QP16MmwE8oZ9Rh5TNPWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
