apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
data:
    token: ENC[AES256_GCM,data:/W1b3Y/obmkJfHYKwyPIfxkP3pERBNBR3feyzXqBT5IrV3OcvxgVsIyPKyykRiPV1T5V8clzQdk2SqBJsKNUzgfOb9u9iMSFvlCWclw0snGdcxDmo8BAo9zTEFdF/fKWnGuib1cyYtf5r/9jzamIXacYeIvY7ZuFu4ozEk3zYd8SKz81YuvmX1AerCjpY83EGhCUAJkLRxkQssVCpfTl+bwCiKOdinQeprN3khJ0vXdpE9aHkGd9qdg9huoeOUU6jbIDdbM/1LnKKc6AmbGJlt+4apKn87bamjJNVA88nffBij5MBiv9OFzsochEBidtRI6y5PkI/K/UCeyGlp2dg+DGdjyIsmVqLvEeoPoxEBir6s6bAggmoNIoCEkemGVcs2CzFefprFRxkT4xZZ+9GmplBYNudvd71L6O35QnpQOzdBAJ6hgMzbxRHT00vUrIpL/DN7w7GbQ2YzDpTTTp7EJ6kC8RqAPTbTIDjte0F+aW4DZ3TXqD5xWY2zBixksoe1uRAuRwfIUb1zek2yfOGkhcfL8bVb7W5TFg+KMeOcK59OG8lPfnrZXI2BOHui/odw/J1CLmNnUGY8rM4q93N51rqB2hOHdkuy5vbMHM9aPl0vyhhx1c+T6dYPZVpm2kmPnhYRjFQgX2XqI+v9q9MD6y/rO6bkZv3Q1XuIIvNzWxQaPSYcRYuLEBU9mdZHkEvjx4O6zoV7jmJky1+BcAtwtAXGJNgnia8MVnhrHTf9gSJx59aOUJ01ePQzcuSqA1awuzGEuJ34MSSgZEW7hXL8jHeDhvpfAYbajW9usaK8l7zNr47N3TrwZx5fO5q5vSK6NcKrFSgkkan8msVTCk05gN,iv:wwqBKQaSH8PI37qzyEkBjeVyRRULn9Pv1kyQnAsFbfc=,tag:7yibweuEHFRjCIeZ/yDkyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10tvu775rkn2seez6kkvkdgd7almegdkx5ajqaln5cym80pzspd9sfp3sap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSVZIN3FxNUVMTFhZZkQ1
            RHM4U0xJck90Z1VRcFdHVXRDZXdZbmxTeUJrCmJ6V25yTGlTWXdONTBvWjY5c2dG
            anY4NkZIU2FweFpZcXI0L3VQMmtSYkEKLS0tIFhRWmJlOWp2MElvRXFqTXVhRGF4
            TU9yY3k0VXlWY3daS2ZUanRjb2wwNWsK8Jpgqye4GhUAI1/c2XGahwuovvgp0Mcd
            gfbHajQcbTkLGXcRktRbRt/VU3lX6A7LHhyFE/GzLfDtGEH4f22c9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T13:50:31Z"
    mac: ENC[AES256_GCM,data:Qyjw5V6Sgx7xHb0zx/0mnETcTG4QtRXg0GW2gh+AcjGjpp3PhEDN7A7RvU7fRj998JEbynP2+PX3g9YwRx+dFHC0/34v+wzNHzzpfovcvyTJ3ZiE/J4CDHn4Syhy4FGZ9d3iwlz5ype40NSR6kPH1zmfEdn9n+gQMvzRugpNM7o=,iv:f618BvRmc9wf2ihd52k27wwDqxxKjfuNfpS1Kx3sYUM=,tag:XaroE4IX5VtRK/+E8O6SJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
