apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:S8AuAp8Va4gHYrT7BKbFduIEMd0tuvZX4wvettvz1ZWbhsAmYiBJwmrzts4hNla97Khyc1QhugomTF3VErKbxymlV3mtaiPJriu6CeUSVxK8Sf8NrcBrx9UbDOyOLGIDIULYDDW5QtF0XETa06Ex8g+F9SNoPE1X4Lvj8qmrCTcVmoh9AzU+Soz+RsvEvCq7aMaO7VQfwrKpqlH0VIjtoaNZJupD5b+CGij6H709e2LXFxua+h8t51MJ7oAyaOmzdaEowfHEFufkVx4tW58V1P2otCjYhnWo7zjDzeAQqtuaD418qIwcE1rCMZ/09j2UUpnLqrC01OSHtsIwrPy+T5nax5TiwxESLCjVGjjd1i4NFfL57AYOY76ogx0rPTRqUqtnyL8uHhzjij7LgYH4tSgQ3RIVlZYIHKpw7R+fso4Bhd0yEEhf+RX58h2mOR/sLNhbfoIRT2gIDeitBv+u6W+QGMNmZXdult+CrkdLPytIhF1sVw2IquC3pEULN+wE2/owbpDzFKxqdD1YDM25UM2boEEX284PRgyR6sADbnxzvb29pQ1Sai8H6IIogtK2JCaw6hyTlv3yc8N4dgyZEEBjPp20gnlKkP3Rq/wEllCJ5I1GmiVD8N+1fWGofW5aUZLfxswNvhBwL3phbNuHvkKxWh59DulPeAXBgE5kY896batD0KutK8rQ5o80sv0ogHCCpzDiE6PDg+rfpY1GtVgmM5dOzEJqvwZBo/XqS1pK8+1mDM38KjK1tppoMSaJ0tkuPfzurbsPLi/5lkoNLgKrXwHy4o4R28ZaAnP6ipDhM71BNmpv9qoBJy6sQ9vaQnb8FSjvi/vLbrlVxFb/wyk/maE3IRylMyNUTSfZ/GDd5NntkimUXtTFgVExg1MYuIxyKYh0mDpNzhf6A2x86uEwDL8vnulg75IsN69TRYD1zhSbQfZs1OdeIQCG9WSCce/GytwZTLl2rgd5B0pRAGHkdj9ikA7gNpq0+YR+v8Xgi26fxxLGk04OuKP8HLVkkapP9xwEXyuNVqoaq88BI9mjZ+sScstRXgXYFCoP61m+QK1dM843KVZZGMVs7hhYB/qNg7P6IzYobd/AC4LvI/TwUgvadvt0TjGFhGa3wTJ8350CD4pXFSfwm8i+8CIH6GcUDvGGIrxPB5Y8mRKUn/jQITR8LPUOUoEPZqu2EHclxaDfYjyktKJFCgJRuUIjAYeWr+0Yhyrlq+o2XeXGzXJyVsfD+EBXPcC54v6my2eHVEQ+/OitQHh0qRiyaP+d1B2UlLYLhMqfoKVsN2ZMyXoTDZCJ1erA3dTWCh7+TXumQXBuHEDrPcazNFUWBgEB+xkzxcg3Hc4gahiAZR9yhAnIHgHGC/s8zj1Ei+MFNuK9Wlt0GOAHHNDFAwsb2/vQT1vHzY/zfCFMIAspYFU1pL9vV9WTcbicEyRqsZycuMVnvbIUEFbkJCRHSwR+Dq+X9doVJW5YsHaGZxZdvfCkQK083iYubLQGDncnsgwUWoXB1b4EfAWhaskeN9njqkjV+w2SAxQd9DsHzFHcpC/q7BDxIDZbZYraaeHiwoV2WbDSpNAu4iAMD1BrcEhqfhTpuHtqQ3QjrHL/L9PcQ1h2TEW1tiqmBJQ9KbnXVVQImgivGd8pZXmwcz7JMsqtY0yJK/U+4wna4EpAjzbEhlXFoyHRlV0CcKZxDdeQiDs3pG1mygqSaMhSWr9QIZlrxElAwNOvcOJ1hgXW2m1G//ec3W0NIjSacXsigXRRbwuJfH2IhR9MhFTRP9yzotTL0pJOcOG6x985w4RAXJlO/KIn9xB5OYI8+EYK6pTPMzX+eqTzYisKXkDUXkhNq+16Ac4/kbT3scSLdKgekHcQ/tyX1EDXNMPpD6UWQ+xJm1ZAhNDjibAaWl4J1rjHg7Itm1Et9SO3SLEGsvmk2OxLP31wAWHAlTNSa++OKAXcS20xXEsBx7ds28b7aXU0l7TPLx0oNBshq/2Tt9EzGfpVLtziG3Die6Y=,iv:NRVNWGP/JPn37aQ6QFdtm/QyqqWBpAfUtjsyIfu4+hw=,tag:oL0pcSpgw4o1MxZQGJ4srw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10tvu775rkn2seez6kkvkdgd7almegdkx5ajqaln5cym80pzspd9sfp3sap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTDJMRVFSRHNBUW9tUTNT
            N3ZCOE0rZ25icE0rTm1yQzg0NEZLN21IdEEwCk12Mm5FcGh4RGk2VGtlVU5BN0dX
            NUxsSFgvcEJ1MHQ4TGpoVmZxUnd1R28KLS0tIFJCT2pIVmdNOXEvYlJ0N1NnMVNr
            TUZLMnJBenNSY0lyRy9PQlNoODZkUkkKmi9uXiu5xvVQbfaZZhIcp57V1yR0VDtm
            rKwWZlrYnaOleQDLfvdlFqdGj3br2HWcdL2TvM5clC0MizjsQkuAFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T17:07:39Z"
    mac: ENC[AES256_GCM,data:1XbIWaggCh6VehlUdA6gMkMssPnUJAp4w+CtjB3dNnMevMNi0ODZNGNImfHuXrDS8cJ2QoEaUDdUyUZz73Ra30T7tNoO3/gW58VaZNhDVO7MCp0sk4MIgdGUvMcq/m8YtR/vGEfgXsCgZlRSrBHzaSwFKDz2fM+fBOOHgsyMf2w=,iv:mRnJnPyWBGYvigE8FsVUN2nmNCyfCfjqHWg8WDCyyJo=,tag:NpMprsHLkAY45gtl2g5C5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
