apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
data:
    1password-credentials.json: ENC[AES256_GCM,data:4941RwVQ+dBlPRalT3ELHbtQt8pR9dJxJrWbNehXrQr5A/+f+u2YoFxJ3d+IieswT2czbg72u0cA94z/tJcwmtNYXRe49omGzHuuM5oBkgoa59sKq880BPFWSl5/+tk2iQCJ805QNLLvG36IumZcaETiwAzRaAFExtkfS//DpHuC0isTUziF1RpgE4rtXRWbuaHDRRtEDUMNF+qOjzbgcQ4BzO/+JBNznATVFhLmSHsK9MOr37uuD/64pp9mBtYbPdBuqmbugIYIEC/4w83v/4ZawLQSIuoXSFtcgJF4QwkGqt5X5clm90ROFW+DWY+hvVfvkfZIO3eMBiYv4dd+SnqXDlav2c+n4tT2NfdMqVfZE2x9XJGBwflpmGGJVYeJ/YtidjL5JPt+Hq1CqltD1VpwTgEMx9Ala6cR89bACyfglzc0KVaUm+dA5uwSOD4x1kTaWDe0sjy1j8oDS4rPcatukCP9c2Q/piObPbRhE8GNDVxeXtQV9ulANzfhbV9dRRkklCw9q7bOJBF5kYuEQOPP+vHDIPdFlz8P1QSGiVdgZ7ghjsdYvp9cwaV2avpM0PHob/GasEhs4ayE1qRu1q3n7Zjfa+dex6wnpphFihmw9bBtpgjIn+xY/buQYF9apCpEY9KcYrt/S65R3ATMFkIz0pYx6aASRc8P449yDIIuIdaZQYw6YbmX9LPEHyZhBtcgtA7FP+iJzR3b99yH655f41T6rrEmvYeCq+hHqj79i0zi8N+7XThdOgugY2oke7J2TSCwENjKZDTE9Mec1m2B5zd6rka64/y9uFDpRmiLcTUJ1Z//+Pm1bDDGs2ogoIZzkG9Slb6tkGm7KIFMGWF7H0ju5BhaXuo47nguSviNe8YxKhZVNQwGCyiRA9Nd71QKWtp8ZcFUbm1qEdXI1RYoaBshzjZI0uMbjl+sItKRbp/zEJx4JJcHuAZKRF2YLiDLTp9Yne8kyE3vI8oj3yYmzqHoXeDabFGAWn2YGUNWZnTkUpMvJjI3AhfKxIxtRudeIb1FA/qwfMC9TAqJ/anv5Lvos3lRy+G0yFNUMPMcv1ozDZ9B40FJP/zyf07+NYhBUGP3asFpnwNTDJxtXmJ0lZRzv8lpbRPUZldpCfTG0uWb6W0PUD6Xu+Be5C1gN/zkRkVFLgcY82ze/L8/OYO4Al1p6ZAGryZXUOolohaLCE/BlrXuHlSIGroMPpDtKo09HQUROUHL1IchbSZ/aiB9J+hm+jT8eBFCArdXVAASpklhGKlKEV4de6N0my6RU/5QM5wKS7ZDhkpJCwgJEstkg+b0s8vVyf/OxFqPZ4aoXbKh+kGqbKQ5t3b1sqQ3gWElroGFSmkDPx3TxRtzMIrN6OoEv6+ZfJmjywQnskCNXQHxg2G8buCvagHcR1XadpR+eOe7rFA+XVG/t922hVdigoJ1z1qNAPlZjNexgRkkEfAhEITYemmstxywgFbtAf2mk6EEiRAd1rhoPJHMbtvyuiXgEgmxCYGm9DuwlAogW6zdkmXJILxq5W81fm1t8XJe1Pte55UTnbgy59j8+cOYxoUmUWO8hV0dvFM0Vp6qQNTiizVvea8fF4+9jDr6BFnYqL4WamaMe6n44B7J66IEcNY7RglepvnO5PTxPTX6c5+A0Uh/S6kA1552tyfPHzkJH/MZnJW2iIpuE5A9Kmk0ED7E2dfBImlqZcNge9L5A6S0ElrIgeznpbQzbJSpqSFa/THZqNAoREQJIFxrvuWej00Wd6mXJyUcVxSXz74dcNDBsyZHA06BS2KuopHq68jWc6fpT6ZhVgMPPn9Xz+bsJTq+WXjlEp+SuIDcqQkB9NfY3IgRqwKNAnA8QY/k2VQ0Ko9I4Si809VJL2bEv1ilFi9tJ2izixhLrzqwLwpAeCaXZQn3SJEOzEY5FJ6x0GIYpY7MiRQxDmBnw11gCsMDiYaXdx4En/A2ZMGBi7lKfSgr30NvdJTgZVAiGVBe83WmEJoO7rfG2uYqlumcFA==,iv:xywXGSLriYpaMotHBQDPM9sB60uuWl1fYVV6YPLwwnY=,tag:9grdfucKFs61cLLJSn2q+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10tvu775rkn2seez6kkvkdgd7almegdkx5ajqaln5cym80pzspd9sfp3sap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNzlmUlpRMVZIUXZzbzFa
            N1FuMExyYVdXMnlaRDNOKzdQdElEVURKN0F3CmZ1enNDUEQwWGNNdkl2UUdUcWF6
            QUMwT3pIcmJtNnAyR3VSMHZTL2hydGcKLS0tIEJKVXFLWE9PRGlFcEkzRndnNHQ1
            NmVPOVZrN1E0cytPb3U1djhTWDhMRlkKfOkqGGz6D/zcCu23OTSx6Sn1Jgm6WQ9q
            OU+yfxhun66pE2PggpBPRbXcSaMfsviT6JOheC5/+RW3V2He4lmarQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T13:49:39Z"
    mac: ENC[AES256_GCM,data:bU/dbVIbZBSWp2BUBETsJbKofTs/JSHIpBBhkjR6wlatcfDG1Hb435oqp1BOcTWUrVt72RV+fiudthx2c0nI9WSltqaojnKtIi4wybZb3VEEFls++1xiBOxxb1Mo2AZqY8SBqddtsipWiyPVYEDKgzJ4wuAskAQ1qywxPMfrQVI=,iv:CmeCSm5urGuDknPDt0F97m5/qvQMduQqDNwVATDUnSI=,tag:Cbnu8fNTytl4bmY89glBWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
