apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: renovate-github-key
    namespace: renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: private-key
    remoteRef:
      key: renovate-github-key
      property: "private key"
