apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gregbob.net
spec:
  ingressClassName: external
  rules:
  - host: radarr.gregbob.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: radarr-service
            port:
              number: 7878
