apiVersion: v1
kind: ConfigMap
metadata:
 name: loki-datasource
 namespace: monitoring
 labels:
   grafana_datasource: "1"
data:
 datasource.yaml: |-
   apiVersion: 1
   datasources:
     - name: Loki
       type: loki
       url: http://loki.observability.svc.cluster.local:3100
       access: proxy
       isDefault: false