apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wireguard
  namespace: wireguard
spec:
  interval: 10m
  chart:
    spec:
      chart: wireguard
      version: 0.30.0
      sourceRef:
        kind: HelmRepository
        name: wireguard
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    nodeSelector:
      kubernetes.io/hostname: control-00
    service:
      type: ClusterIP
      port: 51820
      externalTrafficPolicy: "Local"
    secretName: wireguard-privatekey
    wireguard:
      clients:
        - PublicKey: rIvNp5lC7V5CGDXO+Nuktu6UTwr8nEIpPhmsve4OMiM=
          AllowedIPs: 10.34.0.2/32
    autoscaling:
      enabled: false
    disruptionBudget:
      enabled: false

